### ISSUE TITLE
[Q/A]这个可以完成mysql全/增量到doris吗

### ISSUE THREAD

**Issue by yellowmarlboro** [selectdb/ccr-syncer#35]
如果是同集群的话

**Comment by lcylgs** [comment]
全量可以参考：https://doris.apache.org/zh-CN/docs/dev/ecosystem/mysql-to-doris
增量可以参考：https://doris.apache.org/zh-CN/docs/1.2/data-operate/import/import-way/binlog-load-manual/

**Comment by yellowmarlboro** [comment]
线上的数据一般都是时刻增长的，所以如果我想先同步全量随后转为增量并且保证数据一致性并且可以断点续传的话，有没有成熟的工具？
