### ISSUE TITLE
整库做同步时，表名如果和关键词一致，会出大量报错

### ISSUE THREAD

**Issue by 1Makers1** [selectdb/ccr-syncer#44]
[2024-01-30 15:04:51]  INFO fullsync status: create snapshot job=ccr_test2 line=ccr/job.go:282
[2024-01-30 15:04:51]  INFO create snapshot tpcds.ccrs_tpcds_1706598291 job=ccr_test2 line=base/spec.go:448
[2024-01-30 15:04:51]  WARN job sync failed, job: ccr_test2, err: [normal] Error 1105 (HY000): errCode = 2, detailMessage = Syntax error in line 1:
...talog_sales, store_sales, roles, warehouse, customer_a...
                             ^
Encountered: ROLES
Expected: ROLES is keyword, maybe `ROLES`

backup snapshot ccrs_tpcds_1706598291 failed, sql: BACKUP SNAPSHOT tpcds.ccrs_tpcds_1706598291 TO `__keep_on_local__` ON ( store_returns, catalog_sales_bak, call_center, inventory, promotion, web_page, store_returns_bak, web_returns_bak, web_sales, catalog_returns, catalog_sales, store_sales, roles, warehouse, customer_address, store_sales_bak, customer, test1, store_bak, reason, catalog_returns_bak, item, time_dim, web_returns, date_dim, income_band, catalog_page, store, dbgen_version, household_demographics, ship_mode, customer_demographics, web_site, web_sales_bak ) PROPERTIES ("type" = "full")
github.com/selectdb/ccr_syncer/pkg/ccr/base.(*Spec).CreateSnapshotAndWaitForDone
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/base/spec.go:459
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).fullSync
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job.go:299
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).dbSync
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job.go:1266
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).sync
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job.go:1287
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).run
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job.go:1339
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).Run
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job.go:1405
github.com/selectdb/ccr_syncer/pkg/ccr.(*JobManager).runJob.func1
        /home/doris/workspace/gopath/ccr-syncer/pkg/ccr/job_manager.go:160

**Comment by 1Makers1** [comment]
doris verison 
apache-doris-2.0.3-bin-x64

ccr_syncer verison 
v2.0.3.1-dirty:6a4555f

```sql
CREATE TABLE `roles` (
  role_id       INT,
  occupation    VARCHAR(32),
  camp          VARCHAR(32),
  register_time DATE
)
UNIQUE KEY(role_id)
DISTRIBUTED BY HASH(role_id) BUCKETS 1
PROPERTIES (
  "replication_allocation" = "tag.location.default: 1"
);

INSERT INTO `roles` VALUES
(0, 'who am I', NULL, NULL),
(1, 'mage', 'alliance', '2018-12-03 16:11:28'),
(2, 'paladin', 'alliance', '2018-11-30 16:11:28'),
(3, 'rogue', 'horde', '2018-12-01 16:11:28'),
(4, 'priest', 'alliance', '2018-12-02 16:11:28'),
(5, 'shaman', 'horde', NULL),
(6, 'warrior', 'alliance', NULL),
(7, 'warlock', 'horde', '2018-12-04 16:11:28'),
(8, 'hunter', 'horde', NULL);

**Comment by lsy3993** [comment]
https://github.com/selectdb/ccr-syncer/pull/53

**Comment by w41ter** [comment]
close via #53.
